#!/bin/bash                                                                                                                                                                                                        
                                                                                                                                                                                                                   
# consice way to spin up instances                                                                                                                                                                                 
# step 1. create directory with the same name you want for image and container                                                                                                                                     
# step 2. create Dockerfile with bash entrypoint                                                                                                                                                                   
# step 3. dockgo and your in!                                                                                                                                                                                      
                                                                                                                                                                                                                   
alias dockbuild='docker build -t "${PWD##*/}" .'                                                                                                                                                                   
alias dockrun='docker rm -f "${PWD##*/}" ; docker run -i -d -t --name "${PWD##*/}" "${PWD##*/}"'                                                                                                                   
alias dockattach='docker attach "${PWD##*/}"'                                                                                                                                                                      
alias dockstop='docker stop "${PWD##*/}"'                                                                                                                                                                          
alias dockgo='dockbuild ; dockrun ; dockattach'  
